CREATE TABLE USERS (
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
	LASTNAME VARCHAR (100),
	BIRTHDATE DATE,
	PHONE_NUMBER VARCHAR (20),
	POSTAL_ADDRESS VARCHAR (5),
	MAIL VARCHAR (200),
	SSSS_NUM VARCHAR (15),
    COMPANY_POSITION VARCHAR (150),
	DESC text;
);