CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE USERS_DATA (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    NAME VARCHAR(50),
    LASTNAME VARCHAR(100),
    BIRTHDATE DATE,
    PHONE_NUMBER VARCHAR(20),
    POSTAL_ADDRESS VARCHAR(50),
    MAIL VARCHAR(200) UNIQUE,
    SSSS_NUM VARCHAR(15),
    COMPANY_POSITION VARCHAR(150),
    DESCRIPTION TEXT,
	HOUR_COUNT INT(5),
);

CREATE TABLE users_working_hours (
	id serial PRIMARY KEY,
	user_id INT REFERENCES USERS_DATA(ID),
	hours_left INT,
	hours_worked INT,
	hours_corrected INT,
);